baseURL = 'https://innofactororg.github.io/Azure-Modules/'
languageCode = 'en-us'
title = 'Azure Verified Solutions'
theme = 'hugo-theme-relearn'

images = ['images/avm_logo.png']

enableGitInfo = true

[params]
    base = '/Azure-Verified-Modules'
    images = ['images/avm_logo.png']
    logo = 'images/favicon.svg'
    disableExplicitIndexURLs = true
    disableLanguageSwitchingButton = false
    themeVariant = [
        { identifier = 'auto', name = 'Zen Light/Dark', auto = [ 'zen-light', 'zen-dark' ] },
        { identifier = 'zen-light'      },
        { identifier = 'zen-dark'       }
    ]
    disableLandingPageButton = false
    landingPageName = '<i class="fa-fw fas fa-home"></i> Home'
    showVisitedLinks = false
    titleSeparator = '|'
    sidebarmenus = [
      { type = 'menu', identifier = 'defined', main = true, disableTitle = true },
      # { type = 'page', identifier = 'home', main = true, disableTitle = true, pageRef = '' },
      # { type = 'menu', identifier = 'shortcuts', main = false, disableTitle = false },
    ]
    editURL = 'https://github.com/innofactororg/Azure-Modules/edit/main/docs/content/${FilePath}'
    disableInlineCopyToClipBoard = true
    disableAnchorScrolling = false
    alwaysopen = true
    collapsibleMenu = false
    disableRootBreadcrumb = false
    # clarityId = 'prb1m4vask' # AVM-Test
    clarityId = 'p0l7yeco82' # Azure-Verified-Modules

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[outputs]
  home = ['html', 'rss', 'print']
  page = ['html', 'rss', 'print']
  section = ['html', 'rss', 'print']

[outputFormats]
  [outputFormats.print]
    baseName = 'print'
    isHTML = true
    mediaType = 'text/html'
    name = 'print'
    noUgly = true
    permalinkable = false

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2

[markup.goldmark.renderer]
    unsafe = true
    hardWraps = true

[markup.goldmark.parser]
  autoHeadingID = true


[[menu.defined]]
  identifier = 'overview'
  parent = 'home'
  name = 'Overview'
  pageRef = '/overview'
  weight = 1
  params = { alwaysopen = true, collapsibleMenu = true }

  [[menu.defined]]
    identifier = 'introduction'
    parent = 'overview'
    name = 'Introduction'
    pageRef = '/overview/introduction'
    weight = 1
    params = { alwaysopen = true, collapsibleMenu = true }

[[menu.defined]]
  identifier = 'module-indexes'
  parent = 'home'
  name = 'Module Indexes'
  pageRef = '/indexes'
  weight = 2
  params = { alwaysopen = true, collapsibleMenu = true }

  [[menu.defined]]
    identifier = 'bicep-module-indexes'
    parent = 'module-indexes'
    name = 'Bicep'
    pageRef = '/indexes/bicep'
    weight = 1
    params = { alwaysopen = true, collapsibleMenu = true }

    [[menu.defined]]
      identifier = 'bicep-resource-module-indexes'
      parent = 'bicep-module-indexes'
      name = 'Resource Modules'
      pageRef = '/indexes/bicep/bicep-resource-modules'
      weight = 1
      params = { alwaysopen = false, collapsibleMenu = true }

    [[menu.defined]]
      identifier = 'bicep-pattern-module-indexes'
      parent = 'bicep-module-indexes'
      name = 'Pattern Modules'
      pageRef = '/indexes/bicep/bicep-pattern-modules'
      weight = 2
      params = { alwaysopen = false, collapsibleMenu = true }

    [[menu.defined]]
      identifier = 'bicep-utility-module-indexes'
      parent = 'bicep-module-indexes'
      name = 'Utility Modules'
      pageRef = '/indexes/bicep/bicep-utility-modules'
      weight = 3
      params = { alwaysopen = false, collapsibleMenu = true }

